version: "3.8"

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: torcoroma_web_app
        environment:
            - APP_NAME=Torcoroma WEB
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=https://torcoroma.kronnos.dev
            - APP_TIMEZONE=UTC
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=torcoroma_web_project
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - REDIS_CLIENT=phpredis
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - SESSION_DRIVER=database
            - CACHE_STORE=redis
        ports:
            - "127.0.0.1:8080:8000"  # Solo accesible localmente
        volumes:
            - .:/var/www/html
        networks:
            - torcoroma_network
        depends_on:
            - mysql
            - redis
        restart: unless-stopped

    mysql:
        image: mysql:8
        container_name: torcoroma_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: torcoroma_web_project
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - torcoroma_network
        ports:
            - "127.0.0.1:3306:3306"  # Solo accesible localmente
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    redis:
        image: redis:6-alpine
        container_name: torcoroma_redis
        volumes:
            - redis_data:/data
        networks:
            - torcoroma_network
        ports:
            - "127.0.0.1:6379:6379"  # Solo accesible localmente
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

networks:
    torcoroma_network:
        driver: bridge

volumes:
    mysql_data:
    redis_data:
