services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: torcoroma_app
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=torcoroma_mysql
            - DB_PORT=3306
            - DB_DATABASE=torcoroma_web
            - DB_USERNAME=archivemaster
            - DB_PASSWORD=YAXcB61Kcx16A7FBn34k
        volumes:
            - '.:/var/www'
            - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - torcoroma_network
    nginx:
        image: 'nginx:alpine'
        container_name: torcoroma_nginx
        volumes:
            - '.:/var/www'
            - './docker/nginx:/etc/nginx/conf.d/'
        ports:
            - '8080:80'
        depends_on:
            - app
        networks:
            - torcoroma_network
    mysql:
        image: 'mysql:8.0'
        container_name: torcoroma_mysql
        environment:
            MYSQL_DATABASE: torcoroma_web
            MYSQL_USER: archivemaster
            MYSQL_PASSWORD: YAXcB61Kcx16A7FBn34k
            MYSQL_ROOT_PASSWORD: YAXcB61Kcx16A7FBn34k
        volumes:
            - 'mysql_data:/var/lib/mysql'
        ports:
            - '3308:3306'
        networks:
            - torcoroma_network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-h'
                - localhost
            interval: 10s
            retries: 5
    redis:
        image: 'redis:7-alpine'
        container_name: torcoroma_redis
        volumes:
            - 'redis_data:/data'
        ports:
            - '6381:6379'
        networks:
            - torcoroma_network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
networks:
    torcoroma_network: null
volumes:
    mysql_data: null
    redis_data: null
