name: Deploy Laravel App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 208.109.235.177 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh -i ~/.ssh/id_ed25519 kronnos@208.109.235.177 "cd ~/torcoroma_project && git pull origin master"
        ssh -i ~/.ssh/id_ed25519 kronnos@208.109.235.177 "cd ~/torcoroma_project && docker-compose up -d --build"
        ssh -i ~/.ssh/id_ed25519 kronnos@208.109.235.177 "cd ~/torcoroma_project && docker exec torcoroma_web_app composer install --no-dev --optimize-autoloader --no-interaction"
        ssh -i ~/.ssh/id_ed25519 kronnos@208.109.235.177 "cd ~/torcoroma_project && docker exec torcoroma_web_app npm ci && npm run build"
        ssh -i ~/.ssh/id_ed25519 kronnos@208.109.235.177 "cd ~/torcoroma_project && docker exec torcoroma_web_app php artisan migrate --force"
        ssh -i ~/.ssh/id_ed25519 kronnos@208.109.235.177 "cd ~/torcoroma_project && docker exec torcoroma_web_app php artisan config:cache"
        ssh -i ~/.ssh/id_ed25519 kronnos@208.109.235.177 "cd ~/torcoroma_project && docker exec torcoroma_web_app php artisan route:cache"
