name: Deploy to Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/torcoroma.kronnos.dev
          git pull origin master
          sudo chown -R www-data:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache
          docker-compose down
          docker-compose up -d --build
          sleep 10  # Espera a que los contenedores estén listos
          docker-compose exec -T app chmod -R 775 /var/www/storage
          docker-compose exec -T app chmod -R 775 /var/www/bootstrap/cache
          docker-compose exec -T app php artisan optimize:clear
          docker-compose exec -T app php artisan migrate --force || true
          docker-compose exec -T app php artisan config:cache
          docker-compose exec -T app php artisan route:cache
